In [1]:
import glob
import pandas

In [2]:
#weather data
weather_df = pandas.read_csv("C:\Users\Rich\Documents\GitHub\CitiBikeApp\data\jfk_temp_data.txt",dtype=str)

In [3]:
# convert date to datetime
weather_df['Date'] = weather_df['Date']+' '+weather_df['HrMn']
weather_df['Date'] = pandas.to_datetime(weather_df['Date'], format='%Y%m%d %H%M')
weather_df = weather_df.drop('HrMn',1)
weather_df = weather_df.drop('QCP',1)
weather_df = weather_df.drop('USAF',1)
weather_df = weather_df.drop('NCDC.',1)
weather_df = weather_df.drop('I',1)
weather_df = weather_df.drop('Type',1)
#weather_df = weather_df.drop('Q',1)
weather_df['Year'] = weather_df['Date'].apply(lambda x: x.year)
weather_df['Month'] = weather_df['Date'].apply(lambda x: x.month)
weather_df['Day'] = weather_df['Date'].apply(lambda x: x.day)
weather_df['Hour'] = weather_df['Date'].apply(lambda x: x.hour)

In [4]:
weather_df

                     Date    Temp Q   Year  Month  Day  Hour
0     2013-07-01 00:00:00    23.3  1  2013      7    1     0
1     2013-07-01 00:49:00    23.0  5  2013      7    1     0
2     2013-07-01 00:51:00    22.8  5  2013      7    1     0
3     2013-07-01 01:05:00    23.0  5  2013      7    1     1
4     2013-07-01 01:51:00    22.2  5  2013      7    1     1
5     2013-07-01 02:49:00    22.0  5  2013      7    1     2
6     2013-07-01 02:51:00    22.2  5  2013      7    1     2
7     2013-07-01 03:00:00    22.2  1  2013      7    1     3
8     2013-07-01 03:49:00    22.0  5  2013      7    1     3
9     2013-07-01 03:51:00    22.2  5  2013      7    1     3
10    2013-07-01 04:43:00    22.0  5  2013      7    1     4
11    2013-07-01 04:51:00    22.2  5  2013      7    1     4
12    2013-07-01 05:05:00    22.0  5  2013      7    1     5
13    2013-07-01 05:26:00    22.0  5  2013      7    1     5
14    2013-07-01 05:49:00    22.0  5  2013      7    1     5
15    2013-07-01 05:51:00    22.2  5  2013      7    1     5
16    2013-07-01 06:00:00    22.2  1  2013      7    1     6
17    2013-07-01 06:14:00    22.0  5  2013      7    1     6
18    2013-07-01 06:51:00    21.7  5  2013      7    1     6
19    2013-07-01 07:51:00    21.7  5  2013      7    1     7
20    2013-07-01 08:51:00    21.7  5  2013      7    1     8
21    2013-07-01 09:00:00    21.7  1  2013      7    1     9
22    2013-07-01 09:51:00    21.7  5  2013      7    1     9
23    2013-07-01 10:51:00    22.2  5  2013      7    1    10
24    2013-07-01 11:51:00    22.2  5  2013      7    1    11
25    2013-07-01 12:00:00    22.2  1  2013      7    1    12
26    2013-07-01 12:17:00    23.0  5  2013      7    1    12
27    2013-07-01 12:49:00    23.0  5  2013      7    1    12
28    2013-07-01 12:51:00    22.8  5  2013      7    1    12
29    2013-07-01 13:51:00    23.9  5  2013      7    1    13
...                   ...     ... ..   ...    ...  ...   ...
31289 2015-12-01 06:38:00     8.0  5  2015     12    1     6
31290 2015-12-01 06:51:00     7.8  5  2015     12    1     6
31291 2015-12-01 07:51:00     8.3  5  2015     12    1     7
31292 2015-12-01 08:51:00     7.8  5  2015     12    1     8
31293 2015-12-01 09:00:00     7.8  1  2015     12    1     9
31294 2015-12-01 09:51:00     7.8  5  2015     12    1     9
31295 2015-12-01 10:02:00     8.0  5  2015     12    1    10
31296 2015-12-01 10:16:00     8.0  5  2015     12    1    10
31297 2015-12-01 10:51:00     8.3  5  2015     12    1    10
31298 2015-12-01 11:49:00     8.0  5  2015     12    1    11
31299 2015-12-01 11:51:00     8.3  5  2015     12    1    11
31300 2015-12-01 12:00:00     8.3  1  2015     12    1    12
31301 2015-12-01 12:51:00    10.0  5  2015     12    1    12
31302 2015-12-01 13:51:00    11.1  5  2015     12    1    13
31303 2015-12-01 14:51:00    11.7  5  2015     12    1    14
31304 2015-12-01 15:00:00    11.7  1  2015     12    1    15
31305 2015-12-01 15:49:00    11.0  5  2015     12    1    15
31306 2015-12-01 15:51:00    11.1  5  2015     12    1    15
31307 2015-12-01 16:51:00    11.1  5  2015     12    1    16
31308 2015-12-01 17:51:00    10.6  5  2015     12    1    17
31309 2015-12-01 18:00:00    10.6  1  2015     12    1    18
31310 2015-12-01 18:51:00    10.0  5  2015     12    1    18
31311 2015-12-01 19:21:00    10.0  5  2015     12    1    19
31312 2015-12-01 19:51:00    10.0  5  2015     12    1    19
31313 2015-12-01 20:21:00    10.0  5  2015     12    1    20
31314 2015-12-01 20:51:00     9.4  5  2015     12    1    20
31315 2015-12-01 21:00:00     9.4  1  2015     12    1    21
31316 2015-12-01 21:51:00     9.4  5  2015     12    1    21
31317 2015-12-01 22:51:00     9.4  5  2015     12    1    22
31318 2015-12-01 23:51:00     9.4  5  2015     12    1    23

[31319 rows x 7 columns]

In [5]:
weather_df['Temp'] = weather_df['Temp'].apply(lambda x: float(x))
#weather_df = weather_df.drop_duplicates(subset=['Year','Month','Day','Hour'], keep='first')
#weather_df = weather_df.drop('Year',1)
#weather_df = weather_df.drop('Month',1)
#weather_df = weather_df.drop('Day',1)
#weather_df = weather_df.drop('Hour',1)
#weather_df['Datemod'] = weather_df['Date'].apply(lambda x: str(x.year)+str(x.month)+str(x.day)+str(x.hour))

In [6]:
weather_df.head()

                 Date  Temp Q   Year  Month  Day  Hour
0 2013-07-01 00:00:00  23.3  1  2013      7    1     0
1 2013-07-01 00:49:00  23.0  5  2013      7    1     0
2 2013-07-01 00:51:00  22.8  5  2013      7    1     0
3 2013-07-01 01:05:00  23.0  5  2013      7    1     1
4 2013-07-01 01:51:00  22.2  5  2013      7    1     1

In [7]:
# make a new dataframe with each row the average temp of the day
#g = weather_df['Temp'].groupby([weather_df['Year'],weather_df['Month'],weather_df['Day']])
#list(g)
test_weather_df = pandas.DataFrame({'avg_temp': weather_df['Temp'].groupby([weather_df['Year'],weather_df['Month'],weather_df['Day']]).mean()}).reset_index()
test_weather_df.head()

   Year  Month  Day   avg_temp
0  2013      7    1  22.808475
1  2013      7    2  22.888000
2  2013      7    3  23.530556
3  2013      7    4  25.092500
4  2013      7    5  25.981250

In [8]:
#g.mean()

In [9]:
import glob

filelist = glob.glob("C:\Users\Rich\Documents\GitHub\CitiBikeApp\data\*.csv")
    

df = pandas.read_csv(filelist[0])

In [2]:
class line:
    def __init__(self, m=None, b=None):
        self.m = m
        self.b = b
    def calculateMandB(self, x1, y1, x2, y2):
        self.m = (y2 - y1)/(x2 - x1)
        self.b = y1 - self.m*x1
    def getY(self, x):
        return self.m*x + self.b

In [5]:
# set up line boundaries
# for upper west side
topline_westside = line()
topline_westside.calculateMandB(40.815368, -73.963737,40.808612, -73.94743)
botline_westside = line()
botline_westside.calculateMandB(40.772222,-73.943607,40.766502,-73.977834)
wesline_westside = line()
wesline_westside.calculateMandB(40.815368, -73.963737,40.772222,-73.943607)
easline_westside = line()
easline_westside.calculateMandB(40.808612, -73.94743,40.766502,-73.977834)

# for upper east side
topline_eastside = line()
topline_eastside.calculateMandB(40.808612, -73.94743, 40.801206,-73.927684)
botline_eastside = line()
botline_eastside.calculateMandB(40.766502,-73.977834,40.75922,-73.957558)
wesline_eastside = line()
wesline_eastside.calculateMandB(40.808612, -73.94743,40.766502,-73.977834)
easline_eastside = line()
easline_eastside.calculateMandB(40.801206,-73.927684,40.75922,-73.957558)

# for midtown
topline_midtown = line()
topline_midtown.calculateMandB(40.772222,-73.943607,40.75922,-73.957558)
botline_midtown = line()
botline_midtown.calculateMandB()
wesline_midtown = line()
wesline_midtown.calculateMandB()
easline_midtown = line()
easline_midtown.calculateMandB()

24.5525753114

In [ ]:
def determineNeighborhood(lat, long):
    lat1 = 
    if lat<40.815368 && lat>40.808612 && lat>

In [10]:
#add the column for the neighborhood code (0: upper west, 1: upper east, 2: midtown, 3: lower west, 4: lower east, 5 governers island, 6 o.w.)
#df.head()
df['neighborhood'] = df['start station latitude'].apply

In [11]:
df['starttime'] = pandas.to_datetime(df['starttime'],format='%Y-%m-%d %H:%M:%S')
#df['Datemod'] = df['starttime'].apply(lambda x: str(x.year)+str(x.month)+str(x.day))
df['Year'] = df['starttime'].apply(lambda x: x.year)
df['Month'] = df['starttime'].apply(lambda x: x.month)
df['Day'] = df['starttime'].apply(lambda x: x.day)
df_grouped = df.groupby([df['Year'],df['Month'],df['Day'],df['start station id']])

In [12]:
df_grouped.count()

                                 tripduration  starttime  stoptime  \
Year Month Day start station id
2013 7     1   72                          55         55        55
               79                          88         88        88
               82                          18         18        18
               83                          30         30        30
               116                         58         58        58
               120                         11         11        11
               127                        106        106       106
               128                         86         86        86
               137                          9          9         9
               143                         23         23        23
               144                         13         13        13
               146                         62         62        62
               147                         78         78        78
               150                         31         31        31
               151                         85         85        85
               152                         32         32        32
               153                         60         60        60
               157                         44         44        44
               160                         22         22        22
               161                         72         72        72
               164                         64         64        64
               167                         77         77        77
               168                         83         83        83
               173                        103        103       103
               174                         32         32        32
               195                         67         67        67
               212                         49         49        49
               216                         14         14        14
               217                         15         15        15
               218                          7          7         7
...                                       ...        ...       ...
           31  527                        142        142       142
               528                        161        161       161
               529                        100        100       100
               531                         91         91        91
               532                         77         77        77
               533                        123        123       123
               534                         54         54        54
               536                        128        128       128
               537                        212        212       212
               538                        106        106       106
               539                         75         75        75
               540                        204        204       204
               545                        127        127       127
               546                        142        142       142
               2000                        88         88        88
               2001                         7          7         7
               2002                        36         36        36
               2003                       104        104       104
               2004                        65         65        65
               2005                         5          5         5
               2006                       171        171       171
               2008                        32         32        32
               2009                        42         42        42
               2010                       109        109       109
               2012                        20         20        20
               2017                        79         79        79
               2021                       182        182       182
               2022                        55         55        55
               2023                        61         61        61
               3002                       128        128       128

                                 start station id  start station name  \
Year Month Day start station id
2013 7     1   72                              55                  55
               79                              88                  88
               82                              18                  18
               83                              30                  30
               116                             58                  58
               120                             11                  11
               127                            106                 106
               128                             86                  86
               137                              9                   9
               143                             23                  23
               144                             13                  13
               146                             62                  62
               147                             78                  78
               150                             31                  31
               151                             85                  85
               152                             32                  32
               153                             60                  60
               157                             44                  44
               160                             22                  22
               161                             72                  72
               164                             64                  64
               167                             77                  77
               168                             83                  83
               173                            103                 103
               174                             32                  32
               195                             67                  67
               212                             49                  49
               216                             14                  14
               217                             15                  15
               218                              7                   7
...                                           ...                 ...
           31  527                            142                 142
               528                            161                 161
               529                            100                 100
               531                             91                  91
               532                             77                  77
               533                            123                 123
               534                             54                  54
               536                            128                 128
               537                            212                 212
               538                            106                 106
               539                             75                  75
               540                            204                 204
               545                            127                 127
               546                            142                 142
               2000                            88                  88
               2001                             7                   7
               2002                            36                  36
               2003                           104                 104
               2004                            65                  65
               2005                             5                   5
               2006                           171                 171
               2008                            32                  32
               2009                            42                  42
               2010                           109                 109
               2012                            20                  20
               2017                            79                  79
               2021                           182                 182
               2022                            55                  55
               2023                            61                  61
               3002                           128                 128

                                 start station latitude  \
Year Month Day start station id
2013 7     1   72                                    55
               79                                    88
               82                                    18
               83                                    30
               116                                   58
               120                                   11
               127                                  106
               128                                   86
               137                                    9
               143                                   23
               144                                   13
               146                                   62
               147                                   78
               150                                   31
               151                                   85
               152                                   32
               153                                   60
               157                                   44
               160                                   22
               161                                   72
               164                                   64
               167                                   77
               168                                   83
               173                                  103
               174                                   32
               195                                   67
               212                                   49
               216                                   14
               217                                   15
               218                                    7
...                                                 ...
           31  527                                  142
               528                                  161
               529                                  100
               531                                   91
               532                                   77
               533                                  123
               534                                   54
               536                                  128
               537                                  212
               538                                  106
               539                                   75
               540                                  204
               545                                  127
               546                                  142
               2000                                  88
               2001                                   7
               2002                                  36
               2003                                 104
               2004                                  65
               2005                                   5
               2006                                 171
               2008                                  32
               2009                                  42
               2010                                 109
               2012                                  20
               2017                                  79
               2021                                 182
               2022                                  55
               2023                                  61
               3002                                 128

                                 start station longitude  end station id  \
Year Month Day start station id
2013 7     1   72                                     55              55
               79                                     88              88
               82                                     18              18
               83                                     30              30
               116                                    58              58
               120                                    11              11
               127                                   106             106
               128                                    86              86
               137                                     9               9
               143                                    23              23
               144                                    13              13
               146                                    62              62
               147                                    78              78
               150                                    31              31
               151                                    85              85
               152                                    32              32
               153                                    60              60
               157                                    44              44
               160                                    22              22
               161                                    72              72
               164                                    64              64
               167                                    77              77
               168                                    83              83
               173                                   103             103
               174                                    32              32
               195                                    67              67
               212                                    49              49
               216                                    14              14
               217                                    15              15
               218                                     7               7
...                                                  ...             ...
           31  527                                   142             142
               528                                   161             161
               529                                   100             100
               531                                    91              91
               532                                    77              77
               533                                   123             123
               534                                    54              54
               536                                   128             128
               537                                   212             212
               538                                   106             106
               539                                    75              75
               540                                   204             204
               545                                   127             127
               546                                   142             142
               2000                                   88              88
               2001                                    7               7
               2002                                   36              36
               2003                                  104             104
               2004                                   65              65
               2005                                    5               5
               2006                                  171             171
               2008                                   32              32
               2009                                   42              42
               2010                                  109             109
               2012                                   20              20
               2017                                   79              79
               2021                                  182             182
               2022                                   55              55
               2023                                   61              61
               3002                                  128             128

                                 end station name  end station latitude  \
Year Month Day start station id
2013 7     1   72                              55                    55
               79                              88                    88
               82                              18                    18
               83                              30                    30
               116                             58                    58
               120                             11                    11
               127                            106                   106
               128                             86                    86
               137                              9                     9
               143                             23                    23
               144                             13                    13
               146                             62                    62
               147                             78                    78
               150                             31                    31
               151                             85                    85
               152                             32                    32
               153                             60                    60
               157                             44                    44
               160                             22                    22
               161                             72                    72
               164                             64                    64
               167                             77                    77
               168                             83                    83
               173                            103                   103
               174                             32                    32
               195                             67                    67
               212                             49                    49
               216                             14                    14
               217                             15                    15
               218                              7                     7
...                                           ...                   ...
           31  527                            142                   142
               528                            161                   161
               529                            100                   100
               531                             91                    91
               532                             77                    77
               533                            123                   123
               534                             54                    54
               536                            128                   128
               537                            212                   212
               538                            106                   106
               539                             75                    75
               540                            204                   204
               545                            127                   127
               546                            142                   142

In [13]:
test_df = pandas.DataFrame({'count': df.groupby([df['Year'],df['Month'],df['Day'],df['start station id']]).size()}).reset_index()

In [14]:
test_df.head()

   Year  Month  Day  start station id  count
0  2013      7    1                72     55
1  2013      7    1                79     88
2  2013      7    1                82     18
3  2013      7    1                83     30
4  2013      7    1               116     58

In [68]:
result = pandas.merge(test_df,test_weather_df,on=['Year','Month','Day'])

In [16]:
result.head()

   Year  Month  Day  start station id  count   avg_temp
0  2013      7    1                72     55  22.808475
1  2013      7    1                79     88  22.808475
2  2013      7    1                82     18  22.808475
3  2013      7    1                83     30  22.808475
4  2013      7    1               116     58  22.808475

In [69]:
# add in a new column for weekday
result['Month'] = result['Month'].apply('{:0>2}'.format)
result['Day'] = result['Day'].apply('{:0>2}'.format)
result['weekday'] = result['Year'].map(str)+'-'+result['Month']+'-'+result['Day']
result['weekday'] = pandas.to_datetime(result['weekday'], format='%Y-%m-%d')
result['weekday'] = result['weekday'].apply(lambda x: x.weekday())
result['start station id'] = result['start station id'].map(str)
#result['avg_temp'] = result['avg_temp'].apply(lambda x: int(round(x)))
result['avg_temp'] = result['avg_temp'].apply(lambda x: float(x))
result['weekday'] = result['weekday'].apply(lambda x: str(x))
result.head()

   Year Month Day start station id  count   avg_temp weekday
0  2013    07  01               72     55  22.808475       0
1  2013    07  01               79     88  22.808475       0
2  2013    07  01               82     18  22.808475       0
3  2013    07  01               83     30  22.808475       0
4  2013    07  01              116     58  22.808475       0

In [18]:
#pandas.get_dummies(result[['start station id','avg_temp','weekday']])

In [74]:
#build a model to take in station id, day of week, and temperature to predict number of riders for a given day
# try a random forest model
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.cross_validation import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import svm
from sklearn.feature_extraction import DictVectorizer as DV

#enc = OneHotEncoder(categorical_features='all', sparse=True)
vectorizer = DV()
datadict = result[['start station id','avg_temp','weekday']].T.to_dict().values()
#print datadict
X_train = vectorizer.fit_transform(datadict)
print X_train
#df_random = result.sample(frac=0.1).reset_index()
#X = result.as_matrix(columns=['start station id', 'avg_temp', 'weekday'])
#print X
#print y
y_train = result['count'].values
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

#amatrix = df_random.as_matrix(columns=['start station id','avg_temp','weekday'])
#print amatrix
#train = enc.fit_transform(amatrix)
#print df_random.head()
#train = df_random.as_matrix(columns=['start station id', 'avg_temp', 'weekday'])
#train = pandas.get_dummies(df_random[['start station id','avg_temp','weekday']]).as_matrix()
#labels = df_random.as_matrix(columns=['count'])
#labels = df_random['count'].values
#labels = df_random.as_matrix(columns=['count']).reshape(len(labels),)
#labels = labels.T
#print train
#print labels
#print len(labels)
rf = RandomForestClassifier(n_estimators=10)
#rf = GaussianNB()
#rf = svm.SVC()
rf.fit(X_train, y_train)
#rf.score(X_test, y_test)

  (0, 0)	22.8084745763
  (0, 326)	1.0
  (0, 330)	1.0
  (1, 0)	22.8084745763
  (1, 327)	1.0
  (1, 330)	1.0
  (2, 0)	22.8084745763
  (2, 328)	1.0
  (2, 330)	1.0
  (3, 0)	22.8084745763
  (3, 329)	1.0
  (3, 330)	1.0
  (4, 0)	22.8084745763
  (4, 1)	1.0
  (4, 330)	1.0
  (5, 0)	22.8084745763
  (5, 3)	1.0
  (5, 330)	1.0
  (6, 0)	22.8084745763
  (6, 4)	1.0
  (6, 330)	1.0
  (7, 0)	22.8084745763
  (7, 5)	1.0
  (7, 330)	1.0
  (8, 0)	22.8084745763
  :	:
  (10128, 332)	1.0
  (10129, 0)	24.071875
  (10129, 32)	1.0
  (10129, 332)	1.0
  (10130, 0)	24.071875
  (10130, 33)	1.0
  (10130, 332)	1.0
  (10131, 0)	24.071875
  (10131, 34)	1.0
  (10131, 332)	1.0
  (10132, 0)	24.071875
  (10132, 35)	1.0
  (10132, 332)	1.0
  (10133, 0)	24.071875
  (10133, 36)	1.0
  (10133, 332)	1.0
  (10134, 0)	24.071875
  (10134, 37)	1.0
  (10134, 332)	1.0
  (10135, 0)	24.071875
  (10135, 38)	1.0
  (10135, 332)	1.0
  (10136, 0)	24.071875
  (10136, 101)	1.0
  (10136, 332)	1.0

MemoryError:

In [62]:
rf.score(X_train, y_train)

0.65785319652722962

In [61]:
print rf.predict(np.array([72,20,2]).reshape(1,-1))

[69]

In [29]:
print rf.feature_importances_

[ 0.92768086  0.03710506  0.03521408]